version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:password@db:5432/testdb
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb -h db -p 5432"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script here

networks:
  app-network:
    driver: bridge
